exception DivByZero;
def foo() : int raises DivByZero {
    try {
        raise DivByZero;
    } except DivByZero {
        print(42);
    }
    return 0;
}
def main() {
    var x = foo() : int;
    print(x);
}
