exception DivByZero;
exception SecondException;

def safe_div(x : int, y:int) : int raises SecondException {
    if (y == 0) {
        raise DivByZero;
    }
    return x / y;
}

def main() {
    try {
        var result = safe_div(10, 0) : int;
        print(result);
    } except DivByZero {
        print(42);
    }
}
